coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
      default:
        threshold: 1%
        target: 0%
    patch: true
    changes: false

comment:
  layout: "header, diff"
  behavior: default