language: node_js

node_js:
  - '6'

sudo: required

services:
  - docker

matrix:
  include:
  - env:
    - BUILD_TASK=build-opencv3.0
    - DOCKER_IMAGE=opencv3.0-node6
  - env:
    - BUILD_TASK=build-opencv3.0-contrib
    - DOCKER_IMAGE=opencv3.0-contrib-node6
  - env:
    - BUILD_TASK=build-opencv3.1
    - DOCKER_IMAGE=opencv3.1-node6
  - env:
    - BUILD_TASK=build-opencv3.1-contrib
    - DOCKER_IMAGE=opencv3.1-contrib-node6
  - env:
    - BUILD_TASK=build-opencv3.3
    - DOCKER_IMAGE=opencv3.3-node6
  - env:
    - BUILD_TASK=build-opencv3.3-contrib
    - DOCKER_IMAGE=opencv3.3-contrib-node6
  - env:
    - BUILD_TASK=build-opencv3.4
    - DOCKER_IMAGE=opencv3.4-node6
  - env:
    - BUILD_TASK=build-opencv3.4-contrib
    - DOCKER_IMAGE=opencv3.4-contrib-node6
  - env:
    - BUILD_TASK=build-opencv3.2-contrib-with-coverage
    - DOCKER_IMAGE=opencv3.2-contrib-node6

install: travis_wait 30 docker pull justadudewhohacks/$DOCKER_IMAGE

script: npm run $BUILD_TASK

after_success:
  - if [ $BUILD_TASK = 'build-opencv3.2-contrib-with-coverage' ]; then
    cd ./ci;
    npm install;
    npm run codecov -- -t $CODECOV_TOKEN;
    fi