language: node_js

sudo: required

services:
  - docker

jobs:
  include:
    - stage: opencv3.0
      script: npm run build-opencv3.0
    - stage: opencv3.1
      script: npm run build-opencv3.1
    - stage: opencv3.3
      script: npm run build-opencv3.3
    - stage: opencv3.2-contrib
      script: npm run build-opencv3.2-contrib-with-coverage

after_success:
  - cd ./ci
  - npm install
  - npm run codecov -- -t $CODECOV_TOKEN