language:
  - cpp

cache:
  - ccache

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git
  - sudo apt-get install -y lcov

  # setup opencv 3.2 with extra modules
  - curl -sL https://github.com/Itseez/opencv/archive/3.2.0.zip > opencv.zip
  - unzip opencv.zip
  - curl -sL https://github.com/Itseez/opencv_contrib/archive/3.2.0.zip > opencv_contrib.zip
  - unzip opencv_contrib.zip

  - cd opencv-3.2.0
  - mkdir build
  - cd build
  - cmake -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.2.0/modules -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j5
  - sudo make install
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - cd ../../

script:
  - npm install
  - cd ./test && npm install && npm run build-debug && npm run cover

after_success:
  - lcov --capture --directory ../build --output-file coverage/capture.info
  - lcov --extract coverage/capture.info '*opencv4nodejs/cc/*' --output-file coverage/extracted.info
  - lcov --test-name opencv4nodejs --add-tracefile coverage/lcov.info --add-tracefile coverage/extracted.info --output-file coverage/opencv4nodejs.info
  - genhtml --output-directory coverage coverage/opencv4nodejs.info