language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git

  # setup opencv 3.2 with extra modules
  - curl -sL https://github.com/Itseez/opencv/archive/3.2.0.zip > opencv.zip
  - unzip opencv.zip
  - curl -sL https://github.com/Itseez/opencv_contrib/archive/3.2.0.zip > opencv_contrib.zip
  - unzip opencv_contrib.zip

  - cd opencv-3.2.0
  - mkdir build
  - cd build
  - cmake -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.2.0/modules -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j5
  - sudo make install
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - cd ../../
  - npm install mocha

script:
  - npm install
  - cd ./test && npm install && npm test