language: node_js

node_js:
  - '6'

sudo: required

services:
  - docker

install: skip

matrix:
  include:
  - env: BUILD_TASK=build-opencv3.0
  - env: BUILD_TASK=build-opencv3.1
  - env: BUILD_TASK=build-opencv3.3
  - env: BUILD_TASK=build-opencv3.2-contrib-with-coverage

script: npm run $BUILD_TASK

after_success:
  - if [ $BUILD_TASK = 'build-opencv3.2-contrib-with-coverage' ]; cd ./ci &&  npm install && npm run codecov -- -t $CODECOV_TOKEN; fi;